### ISSUE TITLE
No error on pinging unreachable host

### ISSUE THREAD

**Issue by desliem** [bluemurder/esp8266-ping#2]
There is a small problem with the library. When pinging a non existing host on the local area network using an IP address, the library returns 0 and not -1. As a result the example program says that the host was reached in 0ms.

Regards.

**Comment by bluemurder** [comment]
Thank you for your report. I'll fix it as soon as possible.

**Comment by bluemurder** [comment]
Please try with last available 1.1.0 version, thank you

**Comment by desliem** [comment]
Everything is fine with the new version. The ping function returns a correct value for reachable and unreachable hosts specified as IP addresses or names. Great.

Thank you
