### ISSUE TITLE
Exception (2): epc1=0x3ffeea88 epc2=0x00000000 - With NodeMcu V3

### ISSUE THREAD

**Issue by 2BECKHAM2** [bluemurder/esp8266-ping#3]
Hi bluemurder,

Thanks for the library.

I'm facing an exception with PingIp. You can find the error and the code below.

..........................
WiFi connected with ip 192.168.0.100
Echo response received from 8.8.8.8 in 48ms.
Echo response received from 8.8.8.8 in 47ms.

Exception (2):
epc1=0x3ffeea88 epc2=0x00000000 epc3=0x00000000 excvaddr=0x3ffeea88 depc=0x00000000

ctx: sys 
sp: 3ffffd40 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffee0:  40226fd6 00000006 00000000 40227006  
3ffffef0:  00000001 00000000 00000000 00000000  
3fffff00:  00000000 00000020 00000407 00000000  
3fffff10:  3ffeec94 3ffefd44 3fff0c6c 40100690  
3fffff20:  00000407 00000000 0000002a 40210150  
3fffff30:  402212bc 3ffecc70 3fff02c4 3ffefd40  
3fffff40:  40226f44 3ffefd44 00000006 4020a1f0  
3fffff50:  3fff0c24 000000c5 00000000 0000002a  
3fffff60:  402287e4 3ffee438 3ffee460 60000600  
3fffff70:  00a6c6c0 3ffee460 3ffee438 402287f1  
3fffff80:  40228836 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee470 3fffdab0 00000000 40202a83  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<
 ets Jan  8 2013,rst cause:2, boot mode:(1,6)
 ets Jan  8 2013,rst cause:4, boot mode:(1,6)
wdt reset

//  CODE //

#include <ESP8266WiFi.h>
#include <WiFiClient.h>
#include <Pinger.h>

void setup()
{  
  Serial.begin(115200);
  delay(10);

  // We start by connecting to a WiFi network

  Serial.println();
  Serial.println("Connecting to WiFi");
  
  WiFi.begin(ssid, password);
  
  while (WiFi.status() != WL_CONNECTED) {
    delay(100);
    Serial.print(".");
  }

  Serial.println();
  Serial.print("WiFi connected with ip ");  
  Serial.println(WiFi.localIP());
} 

void loop()
{
  // Ping Google DNS
  int responseTime = Pinger::Ping(IPAddress(8, 8, 8, 8));
  delay(100);
  // Print it
  if(responseTime == -1)
  {
    Serial.println("Error pinging IP 8.8.8.8");
  }
  else
  {
    Serial.print("Echo response received from 8.8.8.8 in ");
    Serial.print(responseTime);
    Serial.print("ms.\n");
  }

  // Wait a while
  delay(1000);
}

Please let me know at the end of the ping, how do I get the details of "Approximate round trip times in milli-seconds: Minimum, Maximum and Average

Thanks in advance.

**Comment by bluemurder** [comment]
Thank you for your report. I'll fix it as soon as possible.

**Comment by 2BECKHAM2** [comment]
Many thanks for the quick response.

**Comment by bluemurder** [comment]
Hello, thanks for your your report.

For the moment the library provides no functionalities to collect subsequent ping statistics. So to accomplish your requests you can arrange a code like that:

```
...
Pinger pinger;
IPAddress ip(8, 8, 8, 8);
sint32 max_time = 0;
sint32 min_time = 0;
sint32 avg_time = 0;
sint32 response_time;
uint32 tries = 100;
for(uint32 i=0; i<tries; i++)
{
  // Init counters
  if(i == 0)
  {
    max_time = min_time = avg_time = pinger.Ping(ip);
    continue;    
  }

  // Evaluate statistics
  response_time = pinger.Ping(ip);
  if(response_time > max_time) max_time = response_time;
  if(response_time < min_time) min_time = response_time;
  avg_time += response_time;
}

// Evaluate average time
avg_time /= tries;
...
``` 

Remember to handle the case of invalid ping response (when response_time == -1) in order to offer a valid average time calculation.

**Comment by 2BECKHAM2** [comment]
Thanks for the quick response. I still get an Exception(29). 


*******************************************
.....Ok

Exception (29):
epc1=0x40210198 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000014 depc=0x00000000

ctx: cont 
sp: 3ffefa90 end: 3ffefce0 offset: 01a0

>>>stack>>>
3ffefc30:  00000001 3ffefc60 3fffbfac 40226ff3  
3ffefc40:  00000001 00000064 40202a48 3ffeecc0  
3ffefc50:  4020193c 3ffefc90 3ffe84dc 402021e5  
3ffefc60:  00000001 0100a8c0 000003e8 40202168  
3ffefc70:  00000000 00000000 3ffeeaa8 3ffeecb4  
3ffefc80:  3fffdad0 3ffe89f8 0000004a 4020210f  
3ffefc90:  3ffe89f8 0100a8c0 3ffe89f8 0100a8c0  
3ffefca0:  3ffe8900 402023c4 3ffeec88 40202810  
3ffefcb0:  00000000 00000000 00000001 3ffeecb4  
3ffefcc0:  3fffdad0 00000000 3ffeecac 40202a94  
3ffefcd0:  feefeffe feefeffe 3ffeecc0 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)


Any idea on how to go around about this?
Thanks in advance.

**Comment by bluemurder** [comment]
For the moment I have no idea about the error cause, and in my hardware it replicates.
Tried with different delay times between ping requests, and at about 464-466 requests I obtain the same exception.

I investigated also with https://github.com/dancol90/ESP8266Ping library, and also in this case after 499 requests the program seem to freeze.

I will analyze in deep the issue in my free time, but at the moment I have no workaround available

**Comment by 2BECKHAM2** [comment]
Many thanks blue murder for the update.

Will wait.

Thanks & have a nice weekend.

**Comment by bluemurder** [comment]
New 2.0.0 version should fix described issue.

**Comment by 2BECKHAM2** [comment]
Hi, bluemurder,

Thanks a lot for the excellent support and the library.

Have tested with 100, 250, 1200 and 2200 ping count and found to be working fine as expected (No exception observed). The summary details at the end of ping are awesome.

As far as I know, this is one of the most effective ping libraries that I have seen.

****************************
Reply from 8.8.8.8: icmp_seq=1197 bytes=32 time=42ms TTL=46
Reply from 8.8.8.8: icmp_seq=1198 bytes=32 time=53ms TTL=46
Reply from 8.8.8.8: icmp_seq=1199 bytes=32 time=44ms TTL=46
Reply from 8.8.8.8: icmp_seq=1200 bytes=32 time=42ms TTL=46
Ping statistics for 8.8.8.8:
    Packets: Sent = 1200, Received = 1111, Lost = 89 (7.00% loss),
Approximate round trip times in milli-seconds:
    Minimum = 38ms, Maximum = 534ms, Average = 49.82ms
Destination host data:
    IP address: 8.8.8.8

**********************************************************************
Reply from 8.8.8.8: icmp_seq=2197 bytes=32 time=44ms TTL=46
Reply from 8.8.8.8: icmp_seq=2198 bytes=32 time=42ms TTL=46
Reply from 8.8.8.8: icmp_seq=2199 bytes=32 time=40ms TTL=46
Reply from 8.8.8.8: icmp_seq=2200 bytes=32 time=41ms TTL=46
Ping statistics for 8.8.8.8:
    Packets: Sent = 2200, Received = 2100, Lost = 100 (4.00% loss),
Approximate round trip times in milli-seconds:
    Minimum = 38ms, Maximum = 389ms, Average = 51.29ms
Destination host data:
    IP address: 8.8.8.8

**Comment by bluemurder** [comment]
`Packets: Sent = 1200, Received = 1111, Lost = 89 (7.00% loss)`

I have to correct the evaluation of loss percentage, the correct value is 7.42%. 
Thank you again for your report. I close the issue.
